version: "3.9"

services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bcg-data-base
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-ppassword"]
      interval: 3s      # Check every 10 seconds
      timeout: 3s        # Timeout after 5 seconds
      retries: 30        # Retry 3 times before marking as unhealthy
      start_period: 3s   

  flask-app:
    build:
      context: backend
      dockerfile: Dockerfile
    image: flask-app
    container_name: flask-app
    ports:
      - "127.0.0.1:5001:5000"
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql-server:3306/bcg-data-base
    depends_on:
      mysql-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5001/health"]
      interval: 3s      # Check every 10 seconds
      timeout: 3s        # Timeout after 5 seconds
      retries: 30        # Retry 3 times before marking as unhealthy
      start_period: 3s   

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      flask-app:
        condition: service_healthy 

volumes:
  mysql-data:
